import type { CompatibilityMatrixRow, LowStockAlert, PickListResponse } from "../types";

export const DEMO_MATRIX_ROWS: CompatibilityMatrixRow[] = [
  {
    sku: "SP-ENG-000482",
    oemPartNumber: "290569130",
    partName: "Piston Kit STD 150cc",
    category: "Engine",
    crossReferences: [
      { refPartNumber: "290569125", relationship: "SUPERSEDES" },
      { refPartNumber: "AM-PST-150-STD", relationship: "AFTERMARKET_EQUIVALENT" },
    ],
    totalAvailableQty: 36,
    isHeavy: true,
    locations: [{ locationCode: "Z2-A03-R02-S4", zoneType: "SHELVING_STANDARD", availableQty: 36 }],
  },
  {
    sku: "SP-ELE-001120",
    oemPartNumber: "310442087",
    partName: "CDI Unit — Digital Ignition",
    category: "Electrical",
    crossReferences: [{ refPartNumber: "310442080", relationship: "SUPERSEDED_BY" }],
    totalAvailableQty: 6,
    isHeavy: false,
    locations: [{ locationCode: "Z2-A03-R02-S4", zoneType: "SHELVING_STANDARD", availableQty: 6 }],
  },
  {
    sku: "SP-BRK-002391",
    oemPartNumber: "270318452",
    partName: "Front Brake Pad Set (Disc)",
    category: "Braking",
    crossReferences: [],
    totalAvailableQty: 120,
    isHeavy: false,
    locations: [{ locationCode: "Z2-A03-R02-S4", zoneType: "SHELVING_STANDARD", availableQty: 120 }],
  },
];

export const DEMO_LOW_STOCK: LowStockAlert[] = [
  {
    snapshotId: "SP-ELE-001120__Z2-A03-R02-S4",
    sku: "SP-ELE-001120",
    oemPartNumber: "310442087",
    partName: "CDI Unit — Digital Ignition",
    category: "Electrical",
    locationCode: "Z2-A03-R02-S4",
    zoneType: "SHELVING_STANDARD",
    availableQty: 6,
    minThreshold: 10,
    maxThreshold: 80,
    reorderQty: 40,
  },
  {
    snapshotId: "SP-FAS-009902__Z3-A01-R05-S2-BIN07",
    sku: "SP-FAS-009902",
    oemPartNumber: "150118064",
    partName: "M6 Washer — Body Panel Fastening",
    category: "Fasteners_Consumables",
    locationCode: "Z3-A01-R05-S2-BIN07",
    zoneType: "HIGH_DENSITY_MICRO_BIN",
    availableQty: 35,
    minThreshold: 50,
    maxThreshold: 600,
    reorderQty: 300,
  },
  {
    snapshotId: "SP-ELE-004410__Z4-A02-R01-S1",
    sku: "SP-ELE-004410",
    oemPartNumber: "310587120",
    partName: "12V 9Ah Maintenance-Free Battery",
    category: "Electrical",
    locationCode: "Z4-A02-R01-S1",
    zoneType: "HAZMAT_CAGE",
    availableQty: 3,
    minThreshold: 8,
    maxThreshold: 60,
    reorderQty: 30,
  },
];

export const DEMO_PICK_LIST: PickListResponse = {
  orderId: "SO-2026-04471",
  route: [
    {
      sku: "SP-ELE-004410",
      partName: "12V 9Ah Maintenance-Free Battery",
      qtyToPick: 2,
      locationCode: "Z4-A02-R01-S1",
      zoneCode: "Z4",
      zoneLabel: "Hazmat Cage",
      aisle: "A02",
      rack: "R01",
      shelf: "S1",
      displayLabel: "Z4 / A02 / R01 / S1",
      category: "Electrical",
      isHeavy: true,
    },
    {
      sku: "SP-ENG-000482",
      partName: "Piston Kit STD 150cc",
      qtyToPick: 4,
      locationCode: "Z2-A03-R02-S4",
      zoneCode: "Z2",
      zoneLabel: "Standard Shelving",
      aisle: "A03",
      rack: "R02",
      shelf: "S4",
      displayLabel: "Z2 / A03 / R02 / S4",
      category: "Engine",
      isHeavy: true,
    },
    {
      sku: "SP-BRK-002391",
      partName: "Front Brake Pad Set (Disc)",
      qtyToPick: 10,
      locationCode: "Z2-A03-R02-S4",
      zoneCode: "Z2",
      zoneLabel: "Standard Shelving",
      aisle: "A03",
      rack: "R02",
      shelf: "S4",
      displayLabel: "Z2 / A03 / R02 / S4",
      category: "Braking",
      isHeavy: false,
    },
    {
      sku: "SP-FAS-009901",
      partName: "Spark Plug — Standard Heat Range",
      qtyToPick: 20,
      locationCode: "Z3-A01-R05-S2-BIN07",
      zoneCode: "Z3",
      zoneLabel: "High-Density Micro-Bins",
      aisle: "A01",
      rack: "R05",
      shelf: "S2",
      bin: "BIN-07",
      displayLabel: "Z3 / A01 / R05 / S2 / BIN-07",
      category: "Fasteners_Consumables",
      isHeavy: false,
    },
  ],
  shortages: [],
};
